[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "httpx",
    "stripe",
    "flask_limiter",
    "werkzeug",
    "cryptography",
    "flask",
    "markdown"
]
